package com.example.health_management.common.shared.enums;

public enum LoggingType {
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_LOGIN,
    USER_LOGOUT,
    USER_FORGOT_PASSWORD,
    USER_RESET_PASSWORD,
    ARTICLE_CREATED,
    ARTICLE_UPDATED,
    ARTICLE_DELETED,
    ARTICLE_COMMENT_CREATED,
    ARTICLE_COMMENT_DELETED,
    DOCTOR_PROFILE_UPDATED,
    APPOINTMENT_CREATED,
    APPOINTMENT_UPDATED,
    APPOINTMENT_DELETED,
    DOCTOR_SCHEDULE_CREATED,
    DOCTOR_SCHEDULE_UPDATED,
    DOCTOR_SCHEDULE_DELETED,
}
