spring:
  application:
    name: health-management

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  quartz:
    job-store-type: memory
    auto-startup: true
    startup-delay: 0
    overwrite-existing-jobs: true
    properties:
      org.quartz.scheduler.instanceName: HealthManagementScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 5
      org.quartz.threadPool.threadPriority: 5

server:
  port: 8080
  servlet:
    contextPath: /api/v1/core

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always