apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-management-be
  labels:
    app: health-management-be
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-management-be
      version: v1
  template:
    metadata:
      labels:
        app: health-management-be
        version: v1
    spec:
      serviceAccountName: health-management-be-service-account
      containers:
      - name: health-management-be
        image: docker.io/duynguyen03/health-management:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: POSTGRES_HOSTNAME
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: POSTGRES_DB
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: DB_URL
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: REDIS_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: REDIS_PORT
        - name: MAIL_CLIENT_URL
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: MAIL_CLIENT_URL
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        