--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET
statement_timeout = 0;
SET
lock_timeout = 0;
SET
idle_in_transaction_session_timeout = 0;
SET
transaction_timeout = 0;
SET
client_encoding = 'UTF8';
SET
standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET
check_function_bodies = false;
SET
xmloption = content;
SET
client_min_messages = warning;
SET
row_security = off;

SET
default_tablespace = '';

SET
default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts
(
    id             bigint                 NOT NULL,
    created_at     timestamp(6) without time zone NOT NULL,
    deleted_at     timestamp(6) without time zone,
    updated_at     timestamp(6) without time zone,
    email          character varying(100) NOT NULL,
    password       character varying(255) NOT NULL,
    phone          character varying(20),
    role           character varying(20) DEFAULT 'USER'::character varying NOT NULL,
    account_status character varying(20) DEFAULT 'INACTIVE'::character varying NOT NULL,
    username       character varying(50)  NOT NULL,
    user_id        bigint,
    CONSTRAINT accounts_account_status_check CHECK (((account_status)::text = ANY ((ARRAY['ACTIVE':: character varying, 'INACTIVE':: character varying])::text[])
) ),
    CONSTRAINT accounts_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'DOCTOR'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.accounts OWNER TO postgres;

CREATE INDEX idx_accounts_role
    ON public.accounts (user_id, role);
--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activities
(
    id                   bigint NOT NULL,
    created_at           timestamp(6) without time zone NOT NULL,
    deleted_at           timestamp(6) without time zone,
    updated_at           timestamp(6) without time zone,
    activity_description character varying(255),
    activity_name        character varying(255),
    calories_burned      double precision
);


ALTER TABLE public.activities OWNER TO postgres;

--
-- Name: activities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.addresses
(
    id            bigint   NOT NULL,
    created_at    timestamp(6) without time zone NOT NULL,
    deleted_at    timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone,
    address_line1 character varying(255),
    address_line2 character varying(255),
    city          character varying(255),
    country       character varying(255),
    is_default    smallint NOT NULL,
    postal_code   character varying(255),
    region        character varying(255),
    street_number character varying(255),
    unit_number   character varying(255),
    user_id       bigint
);


ALTER TABLE public.addresses OWNER TO postgres;

--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: allergies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.allergies
(
    id           bigint NOT NULL,
    created_at   timestamp(6) without time zone NOT NULL,
    deleted_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone,
    allergy_type smallint,
    note         character varying(255),
    severity     character varying(255),
    user_id      bigint NOT NULL,
    CONSTRAINT allergies_allergy_type_check CHECK (((allergy_type >= 0) AND (allergy_type <= 10)))
);


ALTER TABLE public.allergies OWNER TO postgres;

--
-- Name: allergies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.allergies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.allergies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointment_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointment_records
(
    id                 bigint NOT NULL,
    created_at         timestamp(6) without time zone NOT NULL,
    deleted_at         timestamp(6) without time zone,
    updated_at         timestamp(6) without time zone,
    appointment_type   character varying(20),
    note               character varying(255),
    scheduled_at       timestamp(6) without time zone,
    status             character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    doctor_id          bigint NOT NULL,
    health_provider_id bigint NOT NULL,
    user_id            bigint NOT NULL,
    payment_status     character varying(20) DEFAULT 'INITIAL'::character varying,
    deposit_status     character varying(20) DEFAULT 'NONE'::character varying,
    CONSTRAINT appointment_records_appointment_type_check CHECK (((appointment_type)::text = ANY (ARRAY[('TELEMEDICINE':: character varying)::text, ('IN_PERSON':: character varying)::text]))),
    CONSTRAINT appointment_records_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['INITIAL'::character varying, 'DEPOSITED'::character varying, 'PAID_IN_FULL'::character varying])::text[]))),
    CONSTRAINT appointment_records_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('SCHEDULED'::character varying)::text, ('CANCELLED'::character varying)::text, ('COMPLETED'::character varying)::text]))),
    CONSTRAINT appointment_records_deposit_status_check CHECK (((deposit_status)::text = ANY (ARRAY['NONE'::character varying, 'HOLD'::character varying, 'REFUNDED'::character varying, 'USED'::character varying, 'LOST'::character varying, 'PARTIAL_REFUND_PENDING'::character varying, 'FULL_REFUND_PENDING'::character varying]::text[])))
);


ALTER TABLE public.appointment_records OWNER TO postgres;

--
-- Name: appointment_records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointment_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointment_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX idx_appointment_user_deposit
    ON public.appointment_records (user_id, deposit_status);

--
-- Name: article_comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.article_comments
(
    id             bigint NOT NULL,
    created_at     timestamp(6) without time zone NOT NULL,
    deleted_at     timestamp(6) without time zone,
    updated_at     timestamp(6) without time zone,
    content        text,
    downvote_count integer,
    upvote_count   integer,
    article_id     bigint NOT NULL,
    parent_id      bigint,
    user_id        bigint NOT NULL
);


ALTER TABLE public.article_comments OWNER TO postgres;

--
-- Name: article_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.article_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: article_media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.article_media
(
    id          bigint NOT NULL,
    created_at  timestamp(6) without time zone NOT NULL,
    deleted_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    description character varying(255),
    order_index integer,
    type        character varying(255),
    url         character varying(255),
    article_id  bigint NOT NULL,
    CONSTRAINT article_media_type_check CHECK (((type)::text = ANY ((ARRAY['IMAGE':: character varying, 'VIDEO':: character varying, 'AUDIO':: character varying])::text[])
) )
);


ALTER TABLE public.article_media OWNER TO postgres;

--
-- Name: article_media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.article_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: article_votes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.article_votes
(
    id         bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    type       character varying(255),
    article_id bigint NOT NULL,
    user_id    bigint NOT NULL,
    CONSTRAINT article_votes_type_check CHECK (((type)::text = ANY ((ARRAY['UPVOTE':: character varying, 'DOWNVOTE':: character varying])::text[])
) )
);


ALTER TABLE public.article_votes OWNER TO postgres;

--
-- Name: article_votes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.article_votes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.articles
(
    id              bigint NOT NULL,
    created_at      timestamp(6) without time zone NOT NULL,
    deleted_at      timestamp(6) without time zone,
    updated_at      timestamp(6) without time zone,
    category        character varying(255),
    comment_count   integer,
    content         text,
    down_vote_count integer,
    status          character varying(255),
    title           character varying(255),
    up_vote_count   integer,
    view_count      integer,
    user_id         bigint NOT NULL,
    CONSTRAINT articles_category_check CHECK (((category)::text = ANY ((ARRAY['FITNESS':: character varying, 'NUTRITION':: character varying, 'MENTAL_HEALTH':: character varying, 'LIFESTYLE':: character varying])::text[])
) ),
    CONSTRAINT articles_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))
);


ALTER TABLE public.articles OWNER TO postgres;

--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor_schedules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.doctor_schedules
(
    id                    bigint NOT NULL,
    created_at            timestamp(6) without time zone NOT NULL,
    deleted_at            timestamp(6) without time zone,
    updated_at            timestamp(6) without time zone,
    appointment_status    character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    examination_type      character varying(20),
    note                  character varying(255),
    patient_name          character varying(255),
    start_time            timestamp(6) without time zone,
    doctor_id             bigint,
    appointment_record_id bigint,
    CONSTRAINT doctor_schedules_appointment_status_check CHECK (((appointment_status)::text = ANY (ARRAY[('PENDING':: character varying)::text, ('SCHEDULED':: character varying)::text, ('CANCELLED':: character varying)::text, ('COMPLETED':: character varying)::text])))
);

CREATE INDEX idx_doctor_schedules_appointment_status
    ON public.doctor_schedules (doctor_id, appointment_status);

ALTER TABLE public.doctor_schedules OWNER TO postgres;

--
-- Name: doctor_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.doctor_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.doctors
(
    id                 bigint NOT NULL,
    created_at         timestamp(6) without time zone NOT NULL,
    deleted_at         timestamp(6) without time zone,
    updated_at         timestamp(6) without time zone,
    about              text,
    experience         double precision,
    qualification      character varying(255),
    rating             double precision,
    specialization     character varying(255),
    health_provider_id bigint,
    user_id            bigint,
    CONSTRAINT doctors_specialization_check CHECK (((specialization)::text = ANY ((ARRAY['NEUROLOGIST':: character varying, 'PEDIATRICIAN':: character varying, 'DIETICIAN':: character varying, 'PSYCHOLOGIST':: character varying])::text[])
) )
);


ALTER TABLE public.doctors OWNER TO postgres;

--
-- Name: doctors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.doctors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: health_plans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.health_plans
(
    id         bigint NOT NULL,
    end_date   character varying(255),
    goals      character varying(255),
    notes      character varying(255),
    plan_type  character varying(255),
    start_date character varying(255),
    user_id    bigint,
    CONSTRAINT health_plans_plan_type_check CHECK (((plan_type)::text = ANY ((ARRAY['WEIGHT_LOSS':: character varying, 'WEIGHT_GAIN':: character varying, 'MUSCLE_GAIN':: character varying, 'MAINTAIN':: character varying])::text[])
) )
);


ALTER TABLE public.health_plans OWNER TO postgres;

--
-- Name: health_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.health_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: health_providers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.health_providers
(
    id          bigint NOT NULL,
    created_at  timestamp(6) without time zone NOT NULL,
    deleted_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    description character varying(255),
    name        character varying(255),
    address_id  bigint
);


ALTER TABLE public.health_providers OWNER TO postgres;

--
-- Name: health_providers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.health_providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keys; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.keys
(
    id               bigint                  NOT NULL,
    notification_key character varying(255)  NOT NULL,
    private_key      character varying(4096) NOT NULL,
    public_key       character varying(4096) NOT NULL,
    refresh_token    character varying(4096),
    version          integer                 NOT NULL,
    user_id          bigint
);


ALTER TABLE public.keys OWNER TO postgres;

--
-- Name: keys_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medical_conditions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medical_conditions
(
    id              bigint                NOT NULL,
    created_at      timestamp(6) without time zone NOT NULL,
    deleted_at      timestamp(6) without time zone,
    updated_at      timestamp(6) without time zone,
    condition_name  character varying(255),
    notes           character varying(255),
    status          character varying(20) NOT NULL,
    prescription_id bigint,
    CONSTRAINT medical_conditions_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE':: character varying, 'RESOLVED':: character varying])::text[])
) )
);


ALTER TABLE public.medical_conditions OWNER TO postgres;

--
-- Name: medical_conditions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medical_conditions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_conditions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medications
(
    id          bigint NOT NULL,
    created_at  timestamp(6) without time zone NOT NULL,
    deleted_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    description character varying(255),
    exp_date    date,
    image_url   character varying(255),
    mfg_date    date,
    name        character varying(255)
);


ALTER TABLE public.medications OWNER TO postgres;

--
-- Name: medications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification
(
    id         bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content    character varying(255),
    title      character varying(255),
    user_id    bigint
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescription_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescription_details
(
    id              bigint NOT NULL,
    created_at      timestamp(6) without time zone NOT NULL,
    deleted_at      timestamp(6) without time zone,
    updated_at      timestamp(6) without time zone,
    dosage          character varying(255),
    duration        character varying(255),
    frequency       character varying(255),
    instructions    character varying(255),
    medication_id   bigint,
    prescription_id bigint
);


ALTER TABLE public.prescription_details OWNER TO postgres;

--
-- Name: prescription_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prescription_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescription_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions
(
    id                    bigint NOT NULL,
    created_at            timestamp(6) without time zone NOT NULL,
    deleted_at            timestamp(6) without time zone,
    updated_at            timestamp(6) without time zone,
    diagnosis             character varying(255),
    notes                 character varying(255),
    appointment_record_id bigint
);


ALTER TABLE public.prescriptions OWNER TO postgres;

--
-- Name: prescriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prescriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_metrics
(
    id         bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    age        integer,
    bmi        double precision,
    height     double precision,
    user_id    bigint,
    weight     double precision
);


ALTER TABLE public.user_metrics OWNER TO postgres;

--
-- Name: user_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users
(
    id            bigint NOT NULL,
    created_at    timestamp(6) without time zone NOT NULL,
    deleted_at    timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone,
    avatar_url    character varying(255),
    date_of_birth date,
    first_name    character varying(50),
    gender        character varying(10),
    last_name     character varying(50)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_id_seq', 1, false);


--
-- Name: activities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activities_id_seq', 1, false);


--
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.addresses_id_seq', 1, false);


--
-- Name: allergies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.allergies_id_seq', 1, false);


--
-- Name: appointment_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointment_records_id_seq', 1, false);


--
-- Name: article_comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.article_comments_id_seq', 1, false);


--
-- Name: article_media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.article_media_id_seq', 1, false);


--
-- Name: article_votes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.article_votes_id_seq', 1, false);


--
-- Name: articles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.articles_id_seq', 1, false);


--
-- Name: doctor_schedules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.doctor_schedules_id_seq', 1, false);


--
-- Name: doctors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.doctors_id_seq', 1, false);


--
-- Name: health_plans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.health_plans_id_seq', 1, false);


--
-- Name: health_providers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.health_providers_id_seq', 1, false);


--
-- Name: keys_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.keys_id_seq', 1, false);


--
-- Name: medical_conditions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medical_conditions_id_seq', 1, false);


--
-- Name: medications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medications_id_seq', 1, false);


--
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_id_seq', 1, false);


--
-- Name: prescription_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prescription_details_id_seq', 1, false);


--
-- Name: prescriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prescriptions_id_seq', 1, false);


--
-- Name: user_metrics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_metrics_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: activities activities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: allergies allergies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.allergies
    ADD CONSTRAINT allergies_pkey PRIMARY KEY (id);


--
-- Name: appointment_records appointment_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment_records
    ADD CONSTRAINT appointment_records_pkey PRIMARY KEY (id);


--
-- Name: article_comments article_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_comments
    ADD CONSTRAINT article_comments_pkey PRIMARY KEY (id);


--
-- Name: article_media article_media_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_media
    ADD CONSTRAINT article_media_pkey PRIMARY KEY (id);


--
-- Name: article_votes article_votes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_votes
    ADD CONSTRAINT article_votes_pkey PRIMARY KEY (id);


--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: doctor_schedules doctor_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctor_schedules
    ADD CONSTRAINT doctor_schedules_pkey PRIMARY KEY (id);


--
-- Name: doctors doctors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_pkey PRIMARY KEY (id);


--
-- Name: health_plans health_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_plans
    ADD CONSTRAINT health_plans_pkey PRIMARY KEY (id);


--
-- Name: health_providers health_providers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_providers
    ADD CONSTRAINT health_providers_pkey PRIMARY KEY (id);


--
-- Name: keys keys_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.keys
    ADD CONSTRAINT keys_pkey PRIMARY KEY (id);


--
-- Name: medical_conditions medical_conditions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medical_conditions
    ADD CONSTRAINT medical_conditions_pkey PRIMARY KEY (id);


--
-- Name: medications medications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medications
    ADD CONSTRAINT medications_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: prescription_details prescription_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescription_details
    ADD CONSTRAINT prescription_details_pkey PRIMARY KEY (id);


--
-- Name: prescriptions prescriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT prescriptions_pkey PRIMARY KEY (id);


--
-- Name: prescriptions uk62x6xud62ithj3fi884sma9bv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT uk62x6xud62ithj3fi884sma9bv UNIQUE (appointment_record_id);


--
-- Name: article_votes uk6meogjhldjyc4xfleyxb3i7um; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_votes
    ADD CONSTRAINT uk6meogjhldjyc4xfleyxb3i7um UNIQUE (article_id, user_id);


--
-- Name: accounts uke4w4av1wrhanry7t6mxt42nou; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uke4w4av1wrhanry7t6mxt42nou UNIQUE (user_id);


--
-- Name: health_providers ukfibae8nxkocbawlneeg5u3xxp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_providers
    ADD CONSTRAINT ukfibae8nxkocbawlneeg5u3xxp UNIQUE (address_id);


--
-- Name: keys ukfqbd0ji0mujtgfmkwpxrue93e; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.keys
    ADD CONSTRAINT ukfqbd0ji0mujtgfmkwpxrue93e UNIQUE (user_id);


--
-- Name: accounts ukk8h1bgqoplx0rkngj01pm1rgp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT ukk8h1bgqoplx0rkngj01pm1rgp UNIQUE (username);


--
-- Name: accounts ukn7ihswpy07ci568w34q0oi8he; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT ukn7ihswpy07ci568w34q0oi8he UNIQUE (email);


--
-- Name: doctors ukt1f6cueqyjwx5ghew9ar1exe3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT ukt1f6cueqyjwx5ghew9ar1exe3 UNIQUE (user_id);


--
-- Name: user_metrics user_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_metrics
    ADD CONSTRAINT user_metrics_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: article_comments fk14dsxmif4y0tg912k3psxysfp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_comments
    ADD CONSTRAINT fk14dsxmif4y0tg912k3psxysfp FOREIGN KEY (parent_id) REFERENCES public.article_comments(id);


--
-- Name: addresses fk1fa36y2oqhao3wgg2rw1pi459; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fk1fa36y2oqhao3wgg2rw1pi459 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: health_plans fk1vpkka2djb0kx7ykti0k2rjlc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_plans
    ADD CONSTRAINT fk1vpkka2djb0kx7ykti0k2rjlc FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: allergies fk8fq75awqge9jjguhvnpyxu29d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.allergies
    ADD CONSTRAINT fk8fq75awqge9jjguhvnpyxu29d FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: article_comments fk8gyngt3dpovo1ypp3psb7mbs5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_comments
    ADD CONSTRAINT fk8gyngt3dpovo1ypp3psb7mbs5 FOREIGN KEY (article_id) REFERENCES public.articles(id);


--
-- Name: prescription_details fkab9vxya57fdlvcsb91ynnssng; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescription_details
    ADD CONSTRAINT fkab9vxya57fdlvcsb91ynnssng FOREIGN KEY (medication_id) REFERENCES public.medications(id);


--
-- Name: keys fkbu243bwm4nirm8fukfqos9dk9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.keys
    ADD CONSTRAINT fkbu243bwm4nirm8fukfqos9dk9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: article_media fkckjqff4nllfyr8b1vghh74ls3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_media
    ADD CONSTRAINT fkckjqff4nllfyr8b1vghh74ls3 FOREIGN KEY (article_id) REFERENCES public.articles(id);


--
-- Name: appointment_records fkditr7c5agtriq90ge87la0t21; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment_records
    ADD CONSTRAINT fkditr7c5agtriq90ge87la0t21 FOREIGN KEY (doctor_id) REFERENCES public.doctors(id);


--
-- Name: doctors fke9pf5qtxxkdyrwibaevo9frtk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT fke9pf5qtxxkdyrwibaevo9frtk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: prescriptions fkerj55761s5i5awv9lvtg2jv01; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT fkerj55761s5i5awv9lvtg2jv01 FOREIGN KEY (appointment_record_id) REFERENCES public.appointment_records(id);


--
-- Name: article_votes fkfp96891ssdtl6didfedyr0uko; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_votes
    ADD CONSTRAINT fkfp96891ssdtl6didfedyr0uko FOREIGN KEY (article_id) REFERENCES public.articles(id);


--
-- Name: health_providers fkg5nahd1xnlti03vyuc90kqf3w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.health_providers
    ADD CONSTRAINT fkg5nahd1xnlti03vyuc90kqf3w FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- Name: doctors fki6u16v7wwbrj4ee1pwjki5nos; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT fki6u16v7wwbrj4ee1pwjki5nos FOREIGN KEY (health_provider_id) REFERENCES public.health_providers(id);


--
-- Name: appointment_records fkjv674nk98vaqrfikn4eqnjm54; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment_records
    ADD CONSTRAINT fkjv674nk98vaqrfikn4eqnjm54 FOREIGN KEY (health_provider_id) REFERENCES public.health_providers(id);


--
-- Name: medical_conditions fkkjv3pwh4savtdtwb52qsaooat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medical_conditions
    ADD CONSTRAINT fkkjv3pwh4savtdtwb52qsaooat FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id);


--
-- Name: articles fklc3sm3utetrj1sx4v9ahwopnr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT fklc3sm3utetrj1sx4v9ahwopnr FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: article_votes fkmkwrqww9qvsl5jiyqhvvjljl0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_votes
    ADD CONSTRAINT fkmkwrqww9qvsl5jiyqhvvjljl0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: article_comments fkn40omsbuitpr309fymoqidcry; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article_comments
    ADD CONSTRAINT fkn40omsbuitpr309fymoqidcry FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: accounts fknjuop33mo69pd79ctplkck40n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: doctor_schedules fkqptts4sun4tpv6elafrnrfeup; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctor_schedules
    ADD CONSTRAINT fkqptts4sun4tpv6elafrnrfeup FOREIGN KEY (doctor_id) REFERENCES public.doctors(id);


--
-- Name: appointment_records fkrqrcx97gjjfi7j5uko47cq1ha; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment_records
    ADD CONSTRAINT fkrqrcx97gjjfi7j5uko47cq1ha FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: prescription_details fksw4dl29fglymg5hmic0we7gh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescription_details
    ADD CONSTRAINT fksw4dl29fglymg5hmic0we7gh FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id);


--
-- PostgreSQL database dump complete
--

